services:
  redis:
    image: redis/redis-stack-server:latest
    container_name: gokayak-redis
    networks:
      - db-network
    ports:
      - '6379:6379'
  dynamodb:
      image: amazon/dynamodb-local:latest
      container_name: gokayak-dynamodb
      networks:
        - db-network
      ports:
        - '8123:8000'
networks:
  db-network:

